In [2]:
import pandas as pd

In [3]:
import pandas as pd
datacleaning = pd.read_excel(r"C:\Users\DELL\Downloads\datacleaning.xlsx")
print(datacleaning)

    SL.NO  even  odd  multiple5  multiple3  multiple4
0       1   2.0    1          5        3.0          4
1       2   4.0    3         10        6.0          8
2       3   6.0    5         15        9.0         12
3       4   8.0    7         20       12.0         16
4       5  10.0    9         25       15.0         20
5       6  12.0   11         30       18.0         24
6       7  14.0   13         35       21.0         28
7       8  16.0   15         40       24.0         32
8       9  18.0   17         45       27.0         36
9      10  20.0   19         50       30.0         40
10     11   NaN   21         55        NaN         44

In [4]:
datacleaning.head(5)

   SL.NO  even  odd  multiple5  multiple3  multiple4
0      1   2.0    1          5        3.0          4
1      2   4.0    3         10        6.0          8
2      3   6.0    5         15        9.0         12
3      4   8.0    7         20       12.0         16
4      5  10.0    9         25       15.0         20

In [5]:
header = ["SL.NO","even","odd","multiple5","multiple3","multiple4"]
datacleaning.columns = header
datacleaning.head(5)

   SL.NO  even  odd  multiple5  multiple3  multiple4
0      1   2.0    1          5        3.0          4
1      2   4.0    3         10        6.0          8
2      3   6.0    5         15        9.0         12
3      4   8.0    7         20       12.0         16
4      5  10.0    9         25       15.0         20

In [6]:
datacleaning["odd"] = datacleaning["odd"]+1
datacleaning.head(5)

   SL.NO  even  odd  multiple5  multiple3  multiple4
0      1   2.0    2          5        3.0          4
1      2   4.0    4         10        6.0          8
2      3   6.0    6         15        9.0         12
3      4   8.0    8         20       12.0         16
4      5  10.0   10         25       15.0         20

In [7]:
datacleaning["even"] = datacleaning["even"]+1
datacleaning.head(5)
print(datacleaning)

    SL.NO  even  odd  multiple5  multiple3  multiple4
0       1   3.0    2          5        3.0          4
1       2   5.0    4         10        6.0          8
2       3   7.0    6         15        9.0         12
3       4   9.0    8         20       12.0         16
4       5  11.0   10         25       15.0         20
5       6  13.0   12         30       18.0         24
6       7  15.0   14         35       21.0         28
7       8  17.0   16         40       24.0         32
8       9  19.0   18         45       27.0         36
9      10  21.0   20         50       30.0         40
10     11   NaN   22         55        NaN         44

In [8]:
datacleaning.drop([10],axis = 0)

   SL.NO  even  odd  multiple5  multiple3  multiple4
0      1   3.0    2          5        3.0          4
1      2   5.0    4         10        6.0          8
2      3   7.0    6         15        9.0         12
3      4   9.0    8         20       12.0         16
4      5  11.0   10         25       15.0         20
5      6  13.0   12         30       18.0         24
6      7  15.0   14         35       21.0         28
7      8  17.0   16         40       24.0         32
8      9  19.0   18         45       27.0         36
9     10  21.0   20         50       30.0         40

In [9]:
datacleaning = datacleaning.dropna(subset =["even"],axis = 0)
print(datacleaning)

   SL.NO  even  odd  multiple5  multiple3  multiple4
0      1   3.0    2          5        3.0          4
1      2   5.0    4         10        6.0          8
2      3   7.0    6         15        9.0         12
3      4   9.0    8         20       12.0         16
4      5  11.0   10         25       15.0         20
5      6  13.0   12         30       18.0         24
6      7  15.0   14         35       21.0         28
7      8  17.0   16         40       24.0         32
8      9  19.0   18         45       27.0         36
9     10  21.0   20         50       30.0         40

In [10]:
print(datacleaning.index)

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [11]:
datacleaning.describe()

          SL.NO       even        odd  multiple5  multiple3  multiple4
count  10.00000  10.000000  10.000000  10.000000  10.000000  10.000000
mean    5.50000  12.000000  11.000000  27.500000  16.500000  22.000000
std     3.02765   6.055301   6.055301  15.138252   9.082951  12.110601
min     1.00000   3.000000   2.000000   5.000000   3.000000   4.000000
25%     3.25000   7.500000   6.500000  16.250000   9.750000  13.000000
50%     5.50000  12.000000  11.000000  27.500000  16.500000  22.000000
75%     7.75000  16.500000  15.500000  38.750000  23.250000  31.000000
max    10.00000  21.000000  20.000000  50.000000  30.000000  40.000000

In [12]:
datacleaning["multiple5"] = datacleaning["multiple5"].replace(5,"NAN")
datacleaning

   SL.NO  even  odd multiple5  multiple3  multiple4
0      1   3.0    2       NAN        3.0          4
1      2   5.0    4        10        6.0          8
2      3   7.0    6        15        9.0         12
3      4   9.0    8        20       12.0         16
4      5  11.0   10        25       15.0         20
5      6  13.0   12        30       18.0         24
6      7  15.0   14        35       21.0         28
7      8  17.0   16        40       24.0         32
8      9  19.0   18        45       27.0         36
9     10  21.0   20        50       30.0         40

In [13]:
datacleaning["multiple4"] = datacleaning["multiple4"].replace(4,"NAN")
datacleaning

   SL.NO  even  odd multiple5  multiple3 multiple4
0      1   3.0    2       NAN        3.0       NAN
1      2   5.0    4        10        6.0         8
2      3   7.0    6        15        9.0        12
3      4   9.0    8        20       12.0        16
4      5  11.0   10        25       15.0        20
5      6  13.0   12        30       18.0        24
6      7  15.0   14        35       21.0        28
7      8  17.0   16        40       24.0        32
8      9  19.0   18        45       27.0        36
9     10  21.0   20        50       30.0        40

In [14]:
datacleaning.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   SL.NO      10 non-null     int64
 1   even       10 non-null     float64
 2   odd        10 non-null     int64
 3   multiple5  10 non-null     object
 4   multiple3  10 non-null     float64
 5   multiple4  10 non-null     object
dtypes: float64(2), int64(2), object(2)
memory usage: 560.0+ bytes

In [15]:
datacleaning["multiple3"] = datacleaning["multiple3"]/2
datacleaning

   SL.NO  even  odd multiple5  multiple3 multiple4
0      1   3.0    2       NAN        1.5       NAN
1      2   5.0    4        10        3.0         8
2      3   7.0    6        15        4.5        12
3      4   9.0    8        20        6.0        16
4      5  11.0   10        25        7.5        20
5      6  13.0   12        30        9.0        24
6      7  15.0   14        35       10.5        28
7      8  17.0   16        40       12.0        32
8      9  19.0   18        45       13.5        36
9     10  21.0   20        50       15.0        40

In [16]:
datacleaning.rename(columns={"multiple4": "multiple_4"}, inplace=True)
datacleaning

   SL.NO  even  odd multiple5  multiple3 multiple_4
0      1   3.0    2       NAN        1.5        NAN
1      2   5.0    4        10        3.0          8
2      3   7.0    6        15        4.5         12
3      4   9.0    8        20        6.0         16
4      5  11.0   10        25        7.5         20
5      6  13.0   12        30        9.0         24
6      7  15.0   14        35       10.5         28
7      8  17.0   16        40       12.0         32
8      9  19.0   18        45       13.5         36
9     10  21.0   20        50       15.0         40

In [17]:
datacleaning = datacleaning.rename(columns={"multiple4": "multiple_4"})
datacleaning

   SL.NO  even  odd multiple5  multiple3 multiple_4
0      1   3.0    2       NAN        1.5        NAN
1      2   5.0    4        10        3.0          8
2      3   7.0    6        15        4.5         12
3      4   9.0    8        20        6.0         16
4      5  11.0   10        25        7.5         20
5      6  13.0   12        30        9.0         24
6      7  15.0   14        35       10.5         28
7      8  17.0   16        40       12.0         32
8      9  19.0   18        45       13.5         36
9     10  21.0   20        50       15.0         40

In [18]:
datacleaning.rename(columns={"multiple4": "multiple_2"},inplace=True)
datacleaning

   SL.NO  even  odd multiple5  multiple3 multiple_4
0      1   3.0    2       NAN        1.5        NAN
1      2   5.0    4        10        3.0          8
2      3   7.0    6        15        4.5         12
3      4   9.0    8        20        6.0         16
4      5  11.0   10        25        7.5         20
5      6  13.0   12        30        9.0         24
6      7  15.0   14        35       10.5         28
7      8  17.0   16        40       12.0         32
8      9  19.0   18        45       13.5         36
9     10  21.0   20        50       15.0         40

In [19]:
length = [45,43,66,71,32,12,54,67,77,89]
datacleaning["length"] = length
datacleaning

   SL.NO  even  odd multiple5  multiple3 multiple_4  length
0      1   3.0    2       NAN        1.5        NAN      45
1      2   5.0    4        10        3.0          8      43
2      3   7.0    6        15        4.5         12      66
3      4   9.0    8        20        6.0         16      71
4      5  11.0   10        25        7.5         20      32
5      6  13.0   12        30        9.0         24      12
6      7  15.0   14        35       10.5         28      54
7      8  17.0   16        40       12.0         32      67
8      9  19.0   18        45       13.5         36      77
9     10  21.0   20        50       15.0         40      89

In [20]:
datacleaning["length"] = datacleaning["length"]/datacleaning["length"].max()
datacleaning

   SL.NO  even  odd multiple5  multiple3 multiple_4    length
0      1   3.0    2       NAN        1.5        NAN  0.505618
1      2   5.0    4        10        3.0          8  0.483146
2      3   7.0    6        15        4.5         12  0.741573
3      4   9.0    8        20        6.0         16  0.797753
4      5  11.0   10        25        7.5         20  0.359551
5      6  13.0   12        30        9.0         24  0.134831
6      7  15.0   14        35       10.5         28  0.606742
7      8  17.0   16        40       12.0         32  0.752809
8      9  19.0   18        45       13.5         36  0.865169
9     10  21.0   20        50       15.0         40  1.000000

In [21]:
datacleaning.tail()

   SL.NO  even  odd multiple5  multiple3 multiple_4    length
5      6  13.0   12        30        9.0         24  0.134831
6      7  15.0   14        35       10.5         28  0.606742
7      8  17.0   16        40       12.0         32  0.752809
8      9  19.0   18        45       13.5         36  0.865169
9     10  21.0   20        50       15.0         40  1.000000

In [27]:
datacleaning.tail(4)

   SL.NO  even  odd multiple5  multiple3 multiple_4    length
6      7  15.0   14        35       10.5         28  0.606742
7      8  17.0   16        40       12.0         32  0.752809
8      9  19.0   18        45       13.5         36  0.865169
9     10  21.0   20        50       15.0         40  1.000000

In [32]:
import numpy as np
import pandas as pd

bins = np.linspace(datacleaning["length"].min(),
                   datacleaning["length"].max(),
                   4)
print(bins)

# datacleaning["length_category"] = pd.cut(datacleaning["length"], bins=bins)

# print(datacleaning)

[0.13483146 0.42322097 0.71161049 1.        ]

In [30]:
np.linspace(datacleaning["length"].min(),
            datacleaning["length"].max(),
            4)

array([0.13483146, 0.42322097, 0.71161049, 1.        ])